Big Refactor
* Add initial documentation structure and `.gitignore`

* Update dependencies and fix modules that refers `flask.ext`
  * Bugfix: `ModuleNotFoundError: No module named 'flask.ext'`
    * Solution: Import extensions directly by their name instead of through the flask.ext namespace.
    * Reference: https://github.com/pallets/flask/issues/2385

* Update dependencies:
  * Add Pipfile and Pipfile.lock
  * Update requerements.txt

* Bugfix: `BadRequestKeyError`
```
Change from
    value = request.form['data']
to
    value = request.form.get("data")
```

* Add scripts and docs explaining how to configure and run MultiVAC locally

* Bugfix: AttributeError: module 'urllib' has no attribute 'unquote'
  * change from `urllib.unquote()` to `urllib.parse.unquote()`

* Add MultiVAC docker file

* Add Kubernetes manifests (/resources/manifests)

* Add gitlab-ci